# Generated by Django 4.1.1 on 2022-10-14 05:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('payment_dt', models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 14, 11, 10, 40, 679446), null=True, verbose_name='payment_dt')),
                ('payment_success', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Wallet-Transaction',
                'verbose_name_plural': 'Wallet-Transactions',
            },
        ),
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='user')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('payment_dt', models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 14, 11, 10, 40, 679291), null=True, verbose_name='payment_dt')),
                ('payment_success', models.BooleanField(default=False)),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='cards.fundraisingcard', verbose_name='card')),
            ],
            options={
                'verbose_name': 'Donation',
                'verbose_name_plural': 'Donations',
            },
        ),
    ]
