# Generated by Django 4.1.1 on 2022-10-10 22:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donations',
            name='payment_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 11, 4, 0, 46, 180408), null=True, verbose_name='payment_dt'),
        ),
        migrations.AlterField(
            model_name='wallettransactions',
            name='payment_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 11, 4, 0, 46, 180581), null=True, verbose_name='payment_dt'),
        ),
    ]
