# Generated by Django 4.1.1 on 2022-10-13 05:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0004_alter_donations_payment_dt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donations',
            name='payment_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 13, 11, 8, 3, 397943), null=True, verbose_name='payment_dt'),
        ),
        migrations.AlterField(
            model_name='wallettransactions',
            name='payment_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 13, 11, 8, 3, 398133), null=True, verbose_name='payment_dt'),
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('balance_is_active', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
            },
        ),
    ]
