# Generated by Django 4.0.5 on 2022-09-22 22:14

from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='title', max_length=100)),
                ('description', models.TextField(db_column='description', max_length=1000)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('city', models.CharField(max_length=255)),
                ('location', location_field.models.plain.PlainLocationField(max_length=63)),
                ('start_dt', models.DateTimeField(blank=True, db_column='start_dt', null=True)),
                ('end_dt', models.DateTimeField(blank=True, db_column='end_dt', null=True)),
                ('responsibility', models.TextField(db_column='responsibility', max_length=1000)),
                ('requirements', models.TextField(db_column='requirements', max_length=1000)),
            ],
            options={
                'verbose_name': 'Volunteer',
                'verbose_name_plural': 'Volunteers',
                'db_table': 'volunteer',
            },
        ),
        migrations.AlterField(
            model_name='card',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_list', to='cards.category'),
        ),
    ]
