# Generated by Django 4.0.5 on 2022-09-22 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_volunteer_alter_card_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='donations',
            name='region',
            field=models.CharField(blank=True, db_column='region', max_length=100),
        ),
    ]
