# Generated by Django 4.1.1 on 2022-10-13 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_myuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='balance_is_active',
        ),
    ]
