# Generated by Django 4.1.1 on 2022-09-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(db_column='title', max_length=100, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='description',
            field=models.TextField(db_column='description', max_length=1000, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='title',
            field=models.CharField(db_column='title', max_length=100, verbose_name='title'),
        ),
    ]
