# Generated by Django 4.1.1 on 2022-10-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardRequesstModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('description', models.TextField(max_length=1000, verbose_name='description')),
                ('target_amnt', models.FloatField(db_column='target_amnt', default=0, verbose_name='target_amnt')),
                ('deadline', models.DateTimeField(blank=True, db_column='deadline', null=True, verbose_name='deadline')),
                ('contacts', models.TextField(blank=True, db_column='contacts', max_length=500, null=True, verbose_name='contacts')),
            ],
        ),
        migrations.RemoveField(
            model_name='volunteeringcard',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='volunteeringcard',
            name='responsibility',
        ),
        migrations.AlterField(
            model_name='volunteeringcard',
            name='description',
            field=models.TextField(db_column='description', max_length=5000, verbose_name='description'),
        ),
    ]
