# Generated by Django 4.1.1 on 2022-09-22 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_category_photo_alter_category_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='deadline',
            field=models.DateTimeField(blank=True, db_column='deadline', null=True, verbose_name='deadline'),
        ),
        migrations.AlterField(
            model_name='card',
            name='description',
            field=models.TextField(db_column='description', max_length=1000, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='card',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='card',
            name='target_amnt',
            field=models.FloatField(db_column='target_amnt', default=0, verbose_name='target_amnt'),
        ),
        migrations.AlterField(
            model_name='card',
            name='title',
            field=models.CharField(db_column='title', max_length=100, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='card',
            name='total_amnt',
            field=models.FloatField(db_column='total_amnt', default=0, verbose_name='total_amnt'),
        ),
        migrations.AlterField(
            model_name='cardimage',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='donations',
            name='donation_amnt',
            field=models.FloatField(db_column='donation_amnt', default=0, verbose_name='donation_amnt'),
        ),
        migrations.AlterField(
            model_name='donations',
            name='payment_dt',
            field=models.DateTimeField(blank=True, db_column='payment_dt', null=True, verbose_name='payment_dt'),
        ),
    ]
