# Generated by Django 4.1.1 on 2022-10-12 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0003_cardrequesstmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardRequestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('description', models.TextField(max_length=1000, verbose_name='description')),
                ('target_amnt', models.FloatField(db_column='target_amnt', default=0, verbose_name='target_amnt')),
                ('deadline', models.DateTimeField(blank=True, db_column='deadline', null=True, verbose_name='deadline')),
                ('contacts', models.TextField(blank=True, db_column='contacts', max_length=500, null=True, verbose_name='contacts')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CardRequesstModel',
        ),
    ]
