# Generated by Django 4.1.1 on 2022-09-23 01:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0003_alter_card_deadline_alter_card_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='title', max_length=100, verbose_name='title')),
                ('description', models.TextField(db_column='description', max_length=1000, verbose_name='description')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='photo')),
                ('city', models.CharField(max_length=255, verbose_name='city')),
                ('location', location_field.models.plain.PlainLocationField(max_length=63, verbose_name='location')),
                ('start_dt', models.DateTimeField(blank=True, db_column='start_dt', null=True, verbose_name='start_dt')),
                ('end_dt', models.DateTimeField(blank=True, db_column='end_dt', null=True, verbose_name='end_dt')),
                ('responsibility', models.TextField(db_column='responsibility', max_length=1000, verbose_name='responsibility')),
                ('requirements', models.TextField(db_column='requirements', max_length=1000, verbose_name='requirements')),
            ],
            options={
                'verbose_name': 'Volunteer',
                'verbose_name_plural': 'Volunteers',
                'db_table': 'volunteer',
            },
        ),
        migrations.RemoveField(
            model_name='donations',
            name='user_id',
        ),
        migrations.AddField(
            model_name='donations',
            name='region',
            field=models.CharField(blank=True, db_column='region', max_length=100, verbose_name='region'),
        ),
        migrations.AddField(
            model_name='donations',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='card',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_list', to='cards.category'),
        ),
    ]
