# Generated by Django 4.1.1 on 2022-10-05 09:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0004_volunteer_remove_donations_user_id_donations_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.DeleteModel(
            name='Volunteer',
        ),
        migrations.CreateModel(
            name='VolunteerCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='title', max_length=100, verbose_name='title')),
                ('description', models.TextField(db_column='description', max_length=1000, verbose_name='description')),
                ('location', location_field.models.plain.PlainLocationField(max_length=63, verbose_name='location')),
                ('start_dt', models.DateTimeField(blank=True, db_column='start_dt', null=True, verbose_name='start_dt')),
                ('end_dt', models.DateTimeField(blank=True, db_column='end_dt', null=True, verbose_name='end_dt')),
                ('responsibility', models.TextField(db_column='responsibility', max_length=1000, verbose_name='responsibility')),
                ('requirements', models.TextField(db_column='requirements', max_length=1000, verbose_name='requirements')),
                ('contacts', models.TextField(db_column='contacts', max_length=500, verbose_name='contacts')),
            ],
            options={
                'verbose_name': 'Volunteer',
                'verbose_name_plural': 'Volunteers',
                'db_table': 'volunteer',
            },
        ),
        migrations.RemoveField(
            model_name='card',
            name='fund',
        ),
        migrations.RemoveField(
            model_name='card',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='card',
            name='total_amnt',
        ),
        migrations.RemoveField(
            model_name='donations',
            name='region',
        ),
        migrations.AddField(
            model_name='card',
            name='contacts',
            field=models.TextField(blank=True, db_column='contacts', max_length=500, null=True, verbose_name='contacts'),
        ),
        migrations.AlterField(
            model_name='card',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_list', to='cards.category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='cardimage',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_images', to='cards.card', verbose_name='card'),
        ),
        migrations.AlterField(
            model_name='donations',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='cards.card', verbose_name='card'),
        ),
        migrations.AlterField(
            model_name='donations',
            name='payment_dt',
            field=models.DateTimeField(blank=True, db_column='payment_dt', default=datetime.datetime(2022, 10, 5, 15, 49, 13, 535080), null=True, verbose_name='payment_dt'),
        ),
        migrations.AlterField(
            model_name='donations',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.DeleteModel(
            name='Fund',
        ),
        migrations.AddField(
            model_name='carddocuments',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_documents', to='cards.card', verbose_name='card'),
        ),
    ]
