# Generated by Django 4.1.1 on 2022-10-12 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_cardrequestmodel_delete_cardrequesstmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardrequestmodel',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='cardrequestmodel',
            name='target_amnt',
        ),
    ]
