# Generated by Django 4.1.1 on 2022-10-07 08:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_volunteer_phone_number_alter_card_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donations',
            name='payment_dt',
            field=models.DateTimeField(blank=True, db_column='payment_dt', default=datetime.datetime(2022, 10, 7, 14, 32, 11, 595060), null=True, verbose_name='payment_dt'),
        ),
    ]
