# Generated by Django 4.1.1 on 2022-10-05 09:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_carddocuments_volunteercard_delete_volunteer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='volunteercard',
            options={'verbose_name': 'Volunteer Card', 'verbose_name_plural': 'Volunteer Cards'},
        ),
        migrations.AlterField(
            model_name='donations',
            name='payment_dt',
            field=models.DateTimeField(blank=True, db_column='payment_dt', default=datetime.datetime(2022, 10, 5, 15, 52, 1, 581189), null=True, verbose_name='payment_dt'),
        ),
        migrations.AlterModelTable(
            name='volunteercard',
            table='volunteer_card',
        ),
    ]
