# Generated by Django 4.1.1 on 2022-10-05 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_alter_volunteercard_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Card',
            new_name='FundraisingCard',
        ),
        migrations.RenameModel(
            old_name='VolunteerCard',
            new_name='VolunteeringCard',
        ),
        migrations.AlterModelOptions(
            name='fundraisingcard',
            options={'verbose_name': 'Fundraising Card', 'verbose_name_plural': 'Fundraising Cards'},
        ),
        migrations.AlterModelOptions(
            name='volunteeringcard',
            options={'verbose_name': 'Volunteering Card', 'verbose_name_plural': 'Volunteering Cards'},
        ),
        migrations.AlterField(
            model_name='donations',
            name='payment_dt',
            field=models.DateTimeField(blank=True, db_column='payment_dt', default=datetime.datetime(2022, 10, 5, 16, 5, 5, 232498), null=True, verbose_name='payment_dt'),
        ),
        migrations.AlterModelTable(
            name='fundraisingcard',
            table='fundraising_card',
        ),
        migrations.AlterModelTable(
            name='volunteeringcard',
            table='volunteering_card',
        ),
    ]
