# Generated by Django 4.1.1 on 2022-10-06 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_rename_card_fundraisingcard_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundraisingcard',
            name='is_urgent',
        ),
        migrations.AlterField(
            model_name='donations',
            name='payment_dt',
            field=models.DateTimeField(blank=True, db_column='payment_dt', default=datetime.datetime(2022, 10, 6, 12, 48, 21, 845108, tzinfo=datetime.timezone.utc), null=True, verbose_name='payment_dt'),
        ),
    ]
