# Generated by Django 4.1.1 on 2022-10-07 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_alter_donations_payment_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donations',
            name='payment_dt',
            field=models.DateTimeField(blank=True, db_column='payment_dt', default=datetime.datetime(2022, 10, 7, 15, 15, 38, 651860), null=True, verbose_name='payment_dt'),
        ),
    ]
